module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  book: 0
  breakpoint: 0
  certificate: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  config_direct_save: 0
  contact: 0
  contextual: 0
  course: 0
  course_book: 0
  course_certificate: 0
  course_content: 0
  course_node: 0
  course_object_manual: 0
  course_quiz: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  h5p: 0
  h5peditor: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  link: 0
  menu_ui: 0
  module_filter: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  pdf_api: 0
  printable: 0
  printable_pdf: 0
  quickedit: 0
  quiz: 0
  quiz_directions: 0
  quiz_long_answer: 0
  quiz_matching: 0
  quiz_page: 0
  quiz_short_answer: 0
  quiz_truefalse: 0
  range: 0
  rdf: 0
  rules: 0
  search: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  typed_data: 0
  update: 0
  user: 0
  views_bulk_operations: 0
  views_ui: 0
  menu_link_content: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
